name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install binaries
        run: |
          npm install -g react-native
          yarn install          
      - name: Bundle binary        
        run: yarn bundle          
        continue-on-error: true
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: v1.0.0
          body: |
            Release notes go here
          draft: false
          prerelease: false
        continue-on-error: true
      - name: Check folders
        run: |
          ls
          cd build
          ls
          cd generated
          ls
          cd android
          ls
        
      - name: Upload binaries
        uses: actions/upload-release-asset@v1     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/generated/android/**
          asset_name: js.bundle
          asset_content_type: application/js
